version: '3'

services:

  mkDocs:
    container_name: mkdocs
    command: serve --dev-addr=0.0.0.0:8000 --no-livereload
    hostname: mkdocs
    image: squidfunk/mkdocs-material:latest
    ports: 
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/docs:ro